---
- name: Update repository indexes
  hosts: all
  become: true
  tasks:
  
    - name: Update repository index (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- name: Install and configure Compute role
  hosts: Compute
  become: true
  roles:
    - Compute

- name: Install and configure Imaging role
  hosts: Imaging
  become: true
  roles:
    - Imaging

- name: Install and configure Identity role
  hosts: Identity
  become: true
  roles:
    - Identity
    
